# Generated by Django 3.2.20 on 2023-08-16 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_profile_profileimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='blankbro.jpg', upload_to='profile_images'),
        ),
    ]
