# Generated by Django 3.2.20 on 2023-08-17 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_likepost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='white.jpg', upload_to='post_images'),
        ),
    ]
