# Generated by Django 4.2.3 on 2023-08-21 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0012_followerscount'),
    ]

    operations = [
        migrations.CreateModel(
            name='form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Surame', models.CharField(max_length=200)),
                ('Age', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Games', models.CharField(choices=[('Football', 'Football'), ('Volleyball', 'Volleyball'), ('Beach Tennis', 'Beach Tennis'), ('Diving', 'Diving'), ('Fishing', 'Fishing'), ('Camping', 'Camping'), ('Beach Yoga', 'Beach Yoga'), ('Beach clean up', 'Beach clean up')], max_length=300)),
                ('location', models.CharField(choices=[('Hassen beach', 'Hassen beach'), ('Hassen beach', 'Hassen beach'), ('Swisri beach', 'Swisri beach'), ('kef lasfer beach', 'kef lasfer beach'), ('Ain Mestir beach', 'Ain Mestir beach'), ('Rafraf beach', 'Rafraf beach')], max_length=300)),
                ('Disponibilité_date', models.DateTimeField()),
                ('requist_date', models.DateTimeField(auto_now_add=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
