# Generated by Django 4.2.3 on 2023-08-21 12:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0013_form'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='form',
            new_name='form_request',
        ),
    ]
