# Generated by Django 4.2.3 on 2023-08-21 13:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_rename_form_form_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_request',
            name='Age',
            field=models.IntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='form_request',
            name='Disponibilité_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
