# Generated by Django 4.2.3 on 2023-08-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_remove_form_request_name_remove_form_request_surame_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form_request',
            old_name='username',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='form_request',
            name='gender',
        ),
        migrations.AddField(
            model_name='form_request',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6),
        ),
    ]
