# Generated by Django 4.2.3 on 2023-08-21 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_rename_username_form_request_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form_request',
            old_name='user',
            new_name='User',
        ),
    ]
