# Generated by Django 4.2.3 on 2023-08-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_form_request_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_request',
            name='Email',
            field=models.EmailField(default='@gamil.com', max_length=254),
        ),
    ]
