# Generated by Django 4.2.3 on 2023-08-21 16:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_form_request_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_request',
            name='Disponibilité_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='form_request',
            name='requist_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
