# Generated by Django 4.2.3 on 2023-08-22 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_profile_bgimg_alter_form_request_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='BGimg',
        ),
        migrations.AddField(
            model_name='post',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
