# Generated by Django 4.2.3 on 2023-08-26 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_postcaption_delete_commentpost_remove_post_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcaption',
            old_name='text',
            new_name='caption',
        ),
    ]
