# Generated by Django 4.2.3 on 2023-08-26 11:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_postcaption_created_at_postcaption_no_of_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcaption',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
