# Generated by Django 4.2.3 on 2023-08-26 11:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_alter_postcaption_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcaption',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
