# Generated by Django 4.2.3 on 2023-08-28 17:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_rename_cap_id_likecap_post_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='commentpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField()),
                ('user', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('post', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
            ],
        ),
    ]
