# Generated by Django 4.2.3 on 2023-08-28 17:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_rename_user_commentpost_auther_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentpost',
            name='post',
        ),
        migrations.AddField(
            model_name='commentpost',
            name='post_id',
            field=models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='blog.post'),
        ),
    ]
