# Generated by Django 4.2.3 on 2023-08-28 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_remove_commentpost_post_commentpost_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentpost',
            name='auther',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post'),
        ),
        migrations.AlterField(
            model_name='commentpost',
            name='post_id',
            field=models.CharField(max_length=50),
        ),
    ]
