# Generated by Django 4.2.3 on 2023-09-06 18:04

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_alter_commentpost_auther'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomGroup',
            fields=[
                ('name', models.CharField(max_length=50, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('caption', models.TextField()),
                ('image', models.ImageField(default='white.jpg', upload_to='group_image')),
                ('user', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('starts_at', models.DateTimeField(blank=True)),
                ('finish_at', models.DateTimeField(blank=True)),
                ('teammates', models.IntegerField(default=1)),
                ('no_of_likes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='joingroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=500)),
                ('username', models.CharField(max_length=100)),
            ],
        ),
    ]
