# Generated by Django 4.2.3 on 2023-09-08 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0039_alter_customgroup_teammates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customgroup',
            name='image',
            field=models.ImageField(upload_to='group_image'),
        ),
    ]
