# Generated by Django 4.2.3 on 2023-09-08 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0042_customgroup_games_customgroup_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customgroup',
            old_name='Games',
            new_name='activity',
        ),
        migrations.AlterField(
            model_name='form_request',
            name='location',
            field=models.CharField(choices=[('Hassen beach', 'Hassen beach'), ('chatmemi beach', 'chatmemi beach'), ('Swisri beach', 'Swisri beach'), ('kef lasfer beach', 'kef lasfer beach'), ('Ain Mestir beach', 'Ain Mestir beach'), ('Rafraf beach', 'Rafraf beach')], max_length=300),
        ),
    ]
