# Generated by Django 3.2.20 on 2023-09-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0043_rename_games_customgroup_activity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customgroup',
            old_name='id',
            new_name='id_grp',
        ),
        migrations.AlterField(
            model_name='customgroup',
            name='image',
            field=models.ImageField(default='white.jpg', upload_to='group_image'),
        ),
    ]
